apiVersion: v1
kind: Service
metadata:
  name: fuzi-bot
  namespace: fuzi
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30100
  selector:
    app: fuzi-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuzi-bot
  namespace: fuzi
spec:
  selector:
    matchLabels:
      app: fuzi-bot
  replicas: 1
  template:
    metadata:
      labels:
        app: fuzi-bot
    spec:
      containers:
        - name: fuzi-bot
          image: 192.168.2.101:5000/fuzi-bot:1.0.0
          ports:
            - containerPort: 80
