apiVersion: v1
kind: Service
metadata:
  name: fuzi-view
  namespace: fuzi
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30100
  selector:
     app: fuzi-view
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuzi-view
  namespace: fuzi
spec:
  selector:
    matchLabels:
      app: fuzi-view
  replicas: 1
  template:
    metadata:
      labels:
        app: fuzi-view
    spec:
      containers:
      - name: fuzi-view
        image: fuzi-view:1.0.0
        ports:
        - containerPort: 80
